# Generated by Django 4.0.4 on 2022-06-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionInf',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名称')),
                ('avatar', models.CharField(default='/static/images/logo_default.jpg', max_length=50, verbose_name='头像位置')),
            ],
            options={
                'db_table': '附加用户信息',
            },
        ),
    ]
