# Generated by Django 4.0.4 on 2022-06-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradditioninf',
            name='avatar',
            field=models.CharField(default='/static/images/user/logo_default.jpg', max_length=50, verbose_name='头像位置'),
        ),
    ]
